export const POSITION_REQUEST = 'POSITION_REQUEST'
export const POSITION_SUCCESS = 'POSITION_SUCCESS'
export const POSITION_FAIL = 'POSITION_FAIL'
export const POSITION_RESET = 'POSITION_RESET'

export const POSITION_CREATE_REQUEST = 'POSITION_CREATE_REQUEST'
export const POSITION_CREATE_SUCCESS = 'POSITION_CREATE_SUCCESS'
export const POSITION_CREATE_FAIL = 'POSITION_CREATE_FAIL'
export const POSITION_CREATE_RESET = 'POSITION_CREATE_RESET'

export const POSITION_UPDATE_REQUEST = 'POSITION_UPDATE_REQUEST'
export const POSITION_UPDATE_SUCCESS = 'POSITION_UPDATE_SUCCESS'
export const POSITION_UPDATE_FAIL = 'POSITION_UPDATE_FAIL'
export const POSITION_UPDATE_RESET = 'POSITION_UPDATE_RESET'

export const POSITION_DELETE_REQUEST = 'POSITION_DELETE_REQUEST'
export const POSITION_DELETE_SUCCESS = 'POSITION_DELETE_SUCCESS'
export const POSITION_DELETE_FAIL = 'POSITION_DELETE_FAIL'
export const POSITION_DELETE_RESET = 'POSITION_DELETE_RESET'
