export const RESIGN_REQUEST = 'RESIGN_REQUEST'
export const RESIGN_SUCCESS = 'RESIGN_SUCCESS'
export const RESIGN_FAIL = 'RESIGN_FAIL'
export const RESIGN_RESET = 'RESIGN_RESET'

export const RESIGN_CREATE_REQUEST = 'RESIGN_CREATE_REQUEST'
export const RESIGN_CREATE_SUCCESS = 'RESIGN_CREATE_SUCCESS'
export const RESIGN_CREATE_FAIL = 'RESIGN_CREATE_FAIL'
export const RESIGN_CREATE_RESET = 'RESIGN_CREATE_RESET'

export const RESIGN_UPDATE_REQUEST = 'RESIGN_UPDATE_REQUEST'
export const RESIGN_UPDATE_SUCCESS = 'RESIGN_UPDATE_SUCCESS'
export const RESIGN_UPDATE_FAIL = 'RESIGN_UPDATE_FAIL'
export const RESIGN_UPDATE_RESET = 'RESIGN_UPDATE_RESET'

export const RESIGN_DELETE_REQUEST = 'RESIGN_DELETE_REQUEST'
export const RESIGN_DELETE_SUCCESS = 'RESIGN_DELETE_SUCCESS'
export const RESIGN_DELETE_FAIL = 'RESIGN_DELETE_FAIL'
export const RESIGN_DELETE_RESET = 'RESIGN_DELETE_RESET'
