export const WRITE_UP_REQUEST = 'WRITE_UP_REQUEST'
export const WRITE_UP_SUCCESS = 'WRITE_UP_SUCCESS'
export const WRITE_UP_FAIL = 'WRITE_UP_FAIL'
export const WRITE_UP_RESET = 'WRITE_UP_RESET'

export const WRITE_UP_CREATE_REQUEST = 'WRITE_UP_CREATE_REQUEST'
export const WRITE_UP_CREATE_SUCCESS = 'WRITE_UP_CREATE_SUCCESS'
export const WRITE_UP_CREATE_FAIL = 'WRITE_UP_CREATE_FAIL'
export const WRITE_UP_CREATE_RESET = 'WRITE_UP_CREATE_RESET'

export const WRITE_UP_UPDATE_REQUEST = 'WRITE_UP_UPDATE_REQUEST'
export const WRITE_UP_UPDATE_SUCCESS = 'WRITE_UP_UPDATE_SUCCESS'
export const WRITE_UP_UPDATE_FAIL = 'WRITE_UP_UPDATE_FAIL'
export const WRITE_UP_UPDATE_RESET = 'WRITE_UP_UPDATE_RESET'

export const WRITE_UP_DELETE_REQUEST = 'WRITE_UP_DELETE_REQUEST'
export const WRITE_UP_DELETE_SUCCESS = 'WRITE_UP_DELETE_SUCCESS'
export const WRITE_UP_DELETE_FAIL = 'WRITE_UP_DELETE_FAIL'
export const WRITE_UP_DELETE_RESET = 'WRITE_UP_DELETE_RESET'
